site_name: atomic-operator
site_description: This python package is used to execute Atomic Red Team tests (Atomics) across multiple operating system environments.
docs_dir: docs
theme:
  name: 'material'
nav:
    - Home: 'index.md'
    - Documentation:
        - 'Get Atomics': 'atomics.md'
        - 'Atomic Operator': 'atomic-operator.md'
        - 'Running Tests on Command Line': 'running-tests-command-line.md'
        - 'Running Tests via Scripts': 'running-tests-script.md'
        - 'Running Tests Remotely On Windows': 'windows-remote.md'
        - 'Running Tests via Configuration File': 'atomic-operator-config.md'
    - Code Reference:
        'Atomic Operator': 'atomic-operator-ref.md'
        'Data Models': 'models-ref.md'
        'Executors': 'execution-ref.md'
    - About:
        - 'License': 'LICENSE.md'
        - 'Contributing': 'CONTRIBUTING.md'
        - 'Changelog': 'CHANGELOG.md'
plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          selection:
            filters:
              - "!^_"  # exlude all members starting with _
              - "^__init__$"  # but always include __init__ modules and methods
  - mike:
      version_selector: true
extra:
  version:
    provider: mike