name: Code Coverage

on: 
  push

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.6]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run Tests on Ubuntu
      run: |
        sudo pip install -r requirements.txt
        sudo pip install -r requirements-dev.txt
        sudo python -m pytest
    - name: Code Coverage on Ubuntu
      run: |
        sudo python -m coverage run -m pytest
        sudo python -m coverage report
    - name: Generating code-coverage badge
      run: |
        sudo pip install coverage-badge
        coverage-badge -o images/coverage.svg -f -q
        if git diff --exit-code images/coverage.svg; then
          git config --local user.email github-actions[bot]@users.noreply.github.com
          git config --local user.name github-actions[bot]
          git add images/coverage.svg --force
          git commit -m "Adding code coverage svg"
        else
          echo "No change in code coverage"
        fi
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: main
